# Generated by Django 4.2.4 on 2023-08-13 02:57

from django.db import migrations, models
import raiseticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('raiseticket', '0002_remove_ticket_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=raiseticket.models.attachment_path, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='filename',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Filename'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
