# Generated by Django 4.2.4 on 2023-08-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiseticket', '0003_alter_ticket_options_ticket_file_ticket_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
    ]
