# Generated by Django 4.2.4 on 2023-08-13 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raiseticket', '0004_alter_ticket_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='FirstName')),
                ('lname', models.CharField(max_length=200, verbose_name='LastName')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('dob', models.DateField(verbose_name='DOB')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('pincode', models.IntegerField(max_length=200, verbose_name='Pincode')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=255, null=True, verbose_name='Gender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='raiseticket.customer'),
            preserve_default=False,
        ),
    ]
