# Generated by Django 4.2.4 on 2023-08-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiseticket', '0005_customer_ticket_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(verbose_name='Pincode'),
        ),
    ]
