# Generated by Django 4.2.4 on 2023-08-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiseticket', '0006_alter_customer_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
    ]
