# Generated by Django 4.2.4 on 2023-08-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raiseticket', '0007_remove_ticket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='raiseticket.customer'),
            preserve_default=False,
        ),
    ]
