# Generated by Django 4.2.4 on 2023-08-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiseticket', '0008_ticket_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
    ]
