# Generated by Django 4.2.4 on 2023-08-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiseticket', '0009_alter_customer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
