# Generated by Django 4.2.4 on 2023-08-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiseticket', '0011_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Email'),
        ),
    ]
