# Generated by Django 4.2.4 on 2023-08-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiseticket', '0012_alter_customer_dob_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
